// Code generated by protoc-gen-http. DO NOT EDIT.
// versions:
//
//	protoc-gen-http dev
//	protoc (unknown)
//
// source: music/v1/artist_service.proto, music/v1/track_service.proto
//
// This file is the runtime's whole input: a route table it executes.
// It parses no templates and reads no descriptors.
//
// grpc-gateway-rs — https://github.com/the-protobuf-project/grpc-gateway-rs
// Package gateway is the generated route table for this API.
//
// Two properties the generator guarantees, both load-bearing:
//
//   - The table is sorted most-specific-first, so a linear scan is correct.
//   - No two routes are ambiguous, checked at build time. An API that cannot be
//     routed unambiguously fails to generate rather than resolving by
//     registration order at request time.
package gateway

import (
	"github.com/the-protobuf-project/grpc-gateway-rs/netadapter/codec"
	"github.com/the-protobuf-project/grpc-gateway-rs/netadapter/route"
)

// Domain is the API's error domain, stamped into every AIP-193 ErrorInfo.
const Domain = "music.example.com"

// The handler index of every method of every service.
//
// One numbering across all services because the route table is one table: a
// request is matched before anything knows which service will serve it.
const (
	// MethodGetArtist is `GET /v1/{name=artists/*}`.
	MethodGetArtist = 0
	// MethodListArtists is `GET /v1/artists`.
	MethodListArtists = 1
	// MethodCreateArtist is `POST /v1/artists with body: "artist"`.
	MethodCreateArtist = 2
	// MethodUpdateArtist is `PATCH /v1/{artist.name=artists/*} with body: "artist"`.
	MethodUpdateArtist = 3
	// MethodDeleteArtist is `DELETE /v1/{name=artists/*}`.
	MethodDeleteArtist = 4
	// MethodGetTrack is `GET /v1/{name=artists/*/tracks/*}`.
	MethodGetTrack = 5
	// MethodListTracks is `GET /v1/{parent=artists/*}/tracks`.
	MethodListTracks = 6
	// MethodCreateTrack is `POST /v1/{parent=artists/*}/tracks with body: "track"`.
	MethodCreateTrack = 7
	// MethodUpdateTrack is `PATCH /v1/{track.name=artists/*/tracks/*} with body: "track"`.
	MethodUpdateTrack = 8
	// MethodDeleteTrack is `DELETE /v1/{name=artists/*/tracks/*}`.
	MethodDeleteTrack = 9
	// MethodWithdrawTrack is `POST /v1/{name=artists/*/tracks/*}:withdraw with body: "*"`.
	MethodWithdrawTrack = 10
	// MethodWatchTracks is `GET /v1/{parent=artists/*}/tracks:watch`.
	MethodWatchTracks = 11
)

// Methods is the method table, in handler-index order.
//
// A matched route resolves to one of these, which is what a runtime reports in
// a tracing span and what a middleware selector dispatches on.
var Methods = []route.Method{
	{
		Name:         "GetArtist",
		FullName:     "music.v1.ArtistService.GetArtist",
		Service:      "music.v1.ArtistService",
		Pattern:      route.PatternGet,
		Mutating:     false,
		ServerStream: false,
	},
	{
		Name:         "ListArtists",
		FullName:     "music.v1.ArtistService.ListArtists",
		Service:      "music.v1.ArtistService",
		Pattern:      route.PatternList,
		Mutating:     false,
		ServerStream: false,
	},
	{
		Name:         "CreateArtist",
		FullName:     "music.v1.ArtistService.CreateArtist",
		Service:      "music.v1.ArtistService",
		Pattern:      route.PatternCreate,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "UpdateArtist",
		FullName:     "music.v1.ArtistService.UpdateArtist",
		Service:      "music.v1.ArtistService",
		Pattern:      route.PatternUpdate,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "DeleteArtist",
		FullName:     "music.v1.ArtistService.DeleteArtist",
		Service:      "music.v1.ArtistService",
		Pattern:      route.PatternDelete,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "GetTrack",
		FullName:     "music.v1.TrackService.GetTrack",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternGet,
		Mutating:     false,
		ServerStream: false,
	},
	{
		Name:         "ListTracks",
		FullName:     "music.v1.TrackService.ListTracks",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternList,
		Mutating:     false,
		ServerStream: false,
	},
	{
		Name:         "CreateTrack",
		FullName:     "music.v1.TrackService.CreateTrack",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternCreate,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "UpdateTrack",
		FullName:     "music.v1.TrackService.UpdateTrack",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternUpdate,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "DeleteTrack",
		FullName:     "music.v1.TrackService.DeleteTrack",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternDelete,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "WithdrawTrack",
		FullName:     "music.v1.TrackService.WithdrawTrack",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternCustom,
		Mutating:     true,
		ServerStream: false,
	},
	{
		Name:         "WatchTracks",
		FullName:     "music.v1.TrackService.WatchTracks",
		Service:      "music.v1.TrackService",
		Pattern:      route.PatternCustom,
		Mutating:     false,
		ServerStream: true,
	},
}

// Codecs is the codec registry this gateway was generated with, default first.
var Codecs = []codec.Entry{
	{
		Name:       "json",
		MediaTypes: []string{"application/json"},
		Framing:    codec.JSONArray,
		Index:      0,
	},
}

// NewTable returns the route table, ready to resolve requests against.
func NewTable() *route.Table { return route.NewTable(Routes, Methods) }

// NewRegistry returns the codec registry.
func NewRegistry() *codec.Registry { return codec.NewRegistry(Codecs) }
