// Code generated by protoc-gen-http. DO NOT EDIT.
// versions:
//
//	protoc-gen-http dev
//	protoc (unknown)
//
// source: music/v1/artist_service.proto, music/v1/track_service.proto
//
// This file is the runtime's whole input: a route table it executes.
// It parses no templates and reads no descriptors.
//
// http — https://github.com/the-protobuf-project/http
package gateway

import "github.com/the-protobuf-project/http/netadapter/route"

// Routes is every binding this API declares, most specific first.
//
// The order is not incidental. The generator sorts by the precedence rules in
// README §1.4 and fails the build on any pair that overlaps without one
// dominating, so the runtime can scan linearly and take the first match.
var Routes = []route.Route{
	{
		Method:   "POST",
		Segments: matchArtistsAnyTracksAny,
		Verb:     "withdraw",
		Captures: captureName1To5,
		Template: "/v1/{name=artists/*/tracks/*}:withdraw",
		Handler:  MethodWithdrawTrack,
	},
	{
		Method:   "DELETE",
		Segments: matchArtistsAnyTracksAny,
		Verb:     "",
		Captures: captureName1To5,
		Template: "/v1/{name=artists/*/tracks/*}",
		Handler:  MethodDeleteTrack,
	},
	{
		Method:   "GET",
		Segments: matchArtistsAnyTracksAny,
		Verb:     "",
		Captures: captureName1To5,
		Template: "/v1/{name=artists/*/tracks/*}",
		Handler:  MethodGetTrack,
	},
	{
		Method:   "PATCH",
		Segments: matchArtistsAnyTracksAny,
		Verb:     "",
		Captures: captureTrackName1To5,
		Template: "/v1/{track.name=artists/*/tracks/*}",
		Handler:  MethodUpdateTrack,
	},
	{
		Method:   "GET",
		Segments: matchArtistsAnyTracks,
		Verb:     "watch",
		Captures: captureParent1To3,
		Template: "/v1/{parent=artists/*}/tracks:watch",
		Handler:  MethodWatchTracks,
	},
	{
		Method:   "POST",
		Segments: matchArtistsAnyTracks,
		Verb:     "",
		Captures: captureParent1To3,
		Template: "/v1/{parent=artists/*}/tracks",
		Handler:  MethodCreateTrack,
	},
	{
		Method:   "GET",
		Segments: matchArtistsAnyTracks,
		Verb:     "",
		Captures: captureParent1To3,
		Template: "/v1/{parent=artists/*}/tracks",
		Handler:  MethodListTracks,
	},
	{
		Method:   "DELETE",
		Segments: matchArtistsAny,
		Verb:     "",
		Captures: captureName1To3,
		Template: "/v1/{name=artists/*}",
		Handler:  MethodDeleteArtist,
	},
	{
		Method:   "GET",
		Segments: matchArtistsAny,
		Verb:     "",
		Captures: captureName1To3,
		Template: "/v1/{name=artists/*}",
		Handler:  MethodGetArtist,
	},
	{
		Method:   "PATCH",
		Segments: matchArtistsAny,
		Verb:     "",
		Captures: captureArtistName1To3,
		Template: "/v1/{artist.name=artists/*}",
		Handler:  MethodUpdateArtist,
	},
	{
		Method:   "POST",
		Segments: matchArtists,
		Verb:     "",
		Captures: noCaptures,
		Template: "/v1/artists",
		Handler:  MethodCreateArtist,
	},
	{
		Method:   "GET",
		Segments: matchArtists,
		Verb:     "",
		Captures: noCaptures,
		Template: "/v1/artists",
		Handler:  MethodListArtists,
	},
}
