// Code generated by protoc-gen-http. DO NOT EDIT.
// versions:
//
//	protoc-gen-http dev
//	protoc (unknown)
//
// source: music/v1/artist_service.proto, music/v1/track_service.proto
//
// This file is the runtime's whole input: a route table it executes.
// It parses no templates and reads no descriptors.
//
// http — https://github.com/the-protobuf-project/http
package routes

import "github.com/the-protobuf-project/http/transcode-go/route"

// The flattened match sequences each route walks.
//
// Shared between routes because several bindings differ only in HTTP method:
// GET, PATCH and DELETE on one resource all walk the same path.
var (
	// matchArtistsAnyTracksAny matches `/v1/artists/*/tracks/*`.
	matchArtistsAnyTracksAny = []route.Match{
		route.Literal("v1"),
		route.Literal("artists"),
		route.Single(),
		route.Literal("tracks"),
		route.Single(),
	}

	// matchArtistsAnyTracks matches `/v1/artists/*/tracks`.
	matchArtistsAnyTracks = []route.Match{
		route.Literal("v1"),
		route.Literal("artists"),
		route.Single(),
		route.Literal("tracks"),
	}

	// matchArtistsAny matches `/v1/artists/*`.
	matchArtistsAny = []route.Match{
		route.Literal("v1"),
		route.Literal("artists"),
		route.Single(),
	}

	// matchArtists matches `/v1/artists`.
	matchArtists = []route.Match{
		route.Literal("v1"),
		route.Literal("artists"),
	}
)

// noCaptures is the empty capture set, for the fully-literal routes.
var noCaptures = []route.Capture{}

// The capture spans, one set per distinct combination of fields and positions.
var (
	// captureName1To5 binds name in /v1/{name=artists/*/tracks/*}:withdraw.
	captureName1To5 = []route.Capture{
		{Field: []string{"name"}, JSON: "name", Start: 1, End: 5},
	}

	// captureTrackName1To5 binds track.name in /v1/{track.name=artists/*/tracks/*}.
	captureTrackName1To5 = []route.Capture{
		{Field: []string{"track", "name"}, JSON: "track.name", Start: 1, End: 5},
	}

	// captureParent1To3 binds parent in /v1/{parent=artists/*}/tracks:watch.
	captureParent1To3 = []route.Capture{
		{Field: []string{"parent"}, JSON: "parent", Start: 1, End: 3},
	}

	// captureName1To3 binds name in /v1/{name=artists/*}.
	captureName1To3 = []route.Capture{
		{Field: []string{"name"}, JSON: "name", Start: 1, End: 3},
	}

	// captureArtistName1To3 binds artist.name in /v1/{artist.name=artists/*}.
	captureArtistName1To3 = []route.Capture{
		{Field: []string{"artist", "name"}, JSON: "artist.name", Start: 1, End: 3},
	}
)
